### ISSUE TITLE
Doesn't seem to run with 3rd party launchers (maybe?)

### ISSUE THREAD

**Issue by Scarlaid** [Matsko3/Elysia-Rich-Presence#2]
Seems like a non-gamer me can't get this to work, maybe because of 3rd party launcher?
Or do you have to login because I just wanna try this out, not really into playing the game 💪

video if needed: https://streamable.com/3gc8d0

**Comment by Matsko3** [comment]
Did you install the requirements packages

**Comment by Scarlaid** [comment]
> Did you install the requirements packages

sorry, which one again? I only install the one form `readme`

**Comment by Matsko3** [comment]
> > Did you install the requirements packages
> 
> sorry, which one again? I only install the one form `readme`

the ones in requirements.txt, also did you try the py file instead of exe?

**Comment by Scarlaid** [comment]
ah, didn't know there was a txt for requirements

as this speaks, I got it to work now, thanks :D
